# -------------------------------------------------------------------------------------------------
# Jekyll Configuration
# -------------------------------------------------------------------------------------------------
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#

# -------------------------------------------------------------------------------------------------
# Site Settings
# -------------------------------------------------------------------------------------------------
title: Imdhemy
email: your-email@example.com
description: |
  I'm a software engineer and customer data expert focused on turning raw data into meaningful, actionable insights.
  I work across the full customer data lifecycle, from clean data capture to behavior-aware models and decisions.
github:
  build_revision: "1.0.0"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://imdhemy.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: imdhemy
github_username: imdhemy
favicon: "/assets/theme/favicon.png"

# -------------------------------------------------------------------------------------------------
# Build settings
# -------------------------------------------------------------------------------------------------
theme: imdhemy-jekyll-theme
exclude:
  - Gemfile
  - Gemfile.lock
  - bin/
  - _drafts

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap
sass:
  quiet_deps: true # Suppress deprecation warnings from Sass

paginate: 7
paginate_path: "/blog/page:num/"
markdown: kramdown
permalink: /blog/:categories/:title:output_ext

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: "archive"
  permalinks:
    tag: '/tag/:name/'
    category: '/category/:name/'

# -------------------------------------------------------------------------------------------------
# Author
# -------------------------------------------------------------------------------------------------
author:
  name: Dhemy
  description: |
    I'm a software engineer and customer data expert focused on turning raw data into meaningful, actionable insights.
    I work across the full customer data lifecycle, from clean data capture to behavior-aware models and decisions.
  avatar: /theme/images/avatar.jpeg

# -------------------------------------------------------------------------------------------------
# Navigation
# -------------------------------------------------------------------------------------------------
navigation:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/blog"
  - title: "About"
    url: "/about"

# -------------------------------------------------------------------------------------------------
# Contributions
# -------------------------------------------------------------------------------------------------
contributions:
  - name: "Laravel"
    url: "https://laravel.com"
    logo: "theme/images/contributions/laravel.png"

  - name: "Spatie"
    url: "https://spatie.be/open-source"
    logo: "theme/images/contributions/spatie.png"

  - name: "OpenSearch"
    url: "https://opensearch.org/"
    logo: "theme/images/contributions/opensearch.png"

  - name: "Google Play Billing"
    url: "https://github.com/imdhemy/google-play-billing"
    logo: "theme/images/contributions/google-play-billing.png"

  - name: "App Store IAP"
    url: "https://github.com/imdhemy/appstore-iap"
    logo: "theme/images/contributions/app-store-iap.png"

  - name: "Laravel In-app Purchase"
    url: "https://imdhemy.com/laravel-iap-docs/"
    logo: "theme/images/contributions/liap.png"

# -------------------------------------------------------------------------------------------------
# Testimonials
# -------------------------------------------------------------------------------------------------
testimonials:
  - name: "Nikolaus Huber"
    description: "Software Architect at Reservix GmbH"
    image: "theme/images/testimonials/niko.jpeg"
    content: |
      While working with Dhemy, I noticed him as a very proficient engineer with a broad knowledge on software 
      engineering and software delivery and strong ownership for what he does. When giving him a task, I was sure 
      that he will take care of it. I also like his willingness to learn new things and that he is also not afraid to
      dive into problems/challenges he has not dealt with before. He also helps others to learn and grow.

  - name: "Carsten Müller"
    description: "Team lead Software Development at Reservix GmbH"
    image: "theme/images/testimonials/carsten.jpeg"
    content: |
      I can wholeheartedly recommend Dhemy as both an exceptional developer and a very good teammate. He 
      combines deep technical expertise with a proactive mindset that consistently drives projects forward.
      I have been particularly impressed by his ability to independently master complex new technologies and 
      translate them into clear technical visions and long-term strategies. 
      Dhemy doesn't just take full ownership of his responsibilities; he is also an outstanding mentor. He always 
      makes time for questions and is deeply committed to helping other developers grow and succeed.

  - name: "Dogan Aydin"
    description: "TurkNet CTO"
    image: "theme/images/testimonials/dogan-aydin.jpg"
    content: |
      I remember the time when we were trying to find senior software developers as it was really challenging. 
      At that time, we met with Mohamad and shared a project with him and wanted him to complete the project. 
      When he shared his source code with us, we found that the source code was quite impressive. 
      he always tries to find the best practice and approach to solve the problems that are given to him. 
      Therefore, he is a really good fit for companies which really care about engineering as Mohamad really cares about
      the structure of source codes, design patterns etc.

  - name: "Obada Qawwas"
    description: "Frontend Tech Lead at Valtech"
    image: "theme/images/testimonials/obada-qawwas.jpg"
    content: |
      Dhemy is one of the best among all people I have ever met and is a loyal colleague who understands complex matters. 
      He is a strong and goal-oriented team player; with every problem, there was a solution. Highly recommended.

  - name: "Abdelrahman Waziry"
    description: "Solutions Architect at TurnDigital"
    image: "theme/images/testimonials/abdelrahman-waziry.jpg"
    content: |
      Dhemy, an exceptional and innovative talent, consistently displays unwavering commitment and dedication in our collaborative projects, setting a stellar example for the ideal programmer.

# -------------------------------------------------------------------------------------------------
# Footer
# -------------------------------------------------------------------------------------------------
footer:
  bg_image: "/images/theme/social.png"
  social:
    - icon: "logo-github"
      url: "https://github.com/imdhemy"
    - icon: "logo-twitter"
      url: "https://twitter.com/imdhemy"
    - icon: "logo-linkedin"
      url: "https://www.linkedin.com/in/imdhemy/"

# -------------------------------------------------------------------------------------------------
# SEO
# -------------------------------------------------------------------------------------------------
theme_seo:
  default_image: "/assets/theme/social-card.png"
  default_image_alt: "Imdhemy personal site social preview"
  twitter_site: "@imdhemy"
  same_as:
    - "https://github.com/imdhemy"
    - "https://twitter.com/imdhemy"
    - "https://www.linkedin.com/in/imdhemy/"

# -------------------------------------------------------------------------------------------------
# Comments & Reactions
# -------------------------------------------------------------------------------------------------
theme_comments:
  enabled: true
  provider: "giscus"
  giscus:
    host: "https://giscus.app"
    repo: "imdhemy/imdhemy.github.io"
    repo_id: "MDEwOlJlcG9zaXRvcnkzNjc1ODI3MjA="
    category: "General"
    category_id: "DIC_kwDOFejeAM4C3865"
    mapping: "pathname"
    term: ""
    strict: "1"
    reactions_enabled: "1"
    emit_metadata: "0"
    input_position: "bottom"
    theme: "light"
    lang: "en"
    loading: "lazy"

# -------------------------------------------------------------------------------------------------
# Certificates
# -------------------------------------------------------------------------------------------------
certificates:
  - title: "Collaborate Effectively for Professional Success"
    issuer: "IBM"
    issuer_logo: "theme/images/certificates/ibm.png"
    issue_date: "November 5, 2025"
    image: "theme/images/certificates/ibm-collaborate-effectively.png"
    image_alt: "IBM Collaborate Effectively for Professional Success Certificate"
    credential_url: "https://www.coursera.org/account/accomplishments/verify/UNWV7YPHWJ0G"
  - title: "Domain Driven Design Made Easy"
    issuer: "Educative"
    issuer_logo: "theme/images/certificates/educative.svg"
    issue_date: "May 19, 2026"
    image: "theme/images/certificates/educative-ddd.png"
    image_alt: "Educative Domain Driven Design Made Easy Certificate"
    credential_url: "https://www.educative.io/verify-certificate/X7HQCQUVDH"
  - title: "Distributed Systems for Practitioners"
    issuer: "Educative"
    issuer_logo: "theme/images/certificates/educative.svg"
    issue_date: "May 28, 2026"
    image: "theme/images/certificates/educative-distributed-systems.png"
    image_alt: "Educative Distributed Systems for Practitioners Certificate"
    credential_url: "https://www.educative.io/verify-certificate/DYZPFWATGY"
