# General settings
title: 'imdhemy'
email: imdhemy@gmail.com
description: "I'm a software-artist. This is my inner voice."
baseurl: ""
url: "https://imdhemy.com"

# Build settings
theme: minima
show_excerpts: false
plugins:
  - jekyll-feed
  - jekyll-postcss-v2
permalink: /blog/:categories/:title:output_ext

nav:
  - title: Home
    path: /

  - title: Blog
    path: /blog

  - title: About
    path: /about

# Cairo theme settings
cairo:
  social_links:
    - title: Twitter
      url: https://twitter.com/imdhemy
    - title: Github
      url: https://github.com/imdhemy
    - title: Linkedin
      url: https://linkedin.com/in/imdhemy


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".

# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - zx/
  - blog.mjs
  - yarn.lock
  - package.json
