# -------------------------------------------------------------------------------------------------
# Jekyll Configuration
# -------------------------------------------------------------------------------------------------
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#

# -------------------------------------------------------------------------------------------------
# Site Settings
# -------------------------------------------------------------------------------------------------
title: Imdhemy
email: your-email@example.com
description: |
  I'm a software artist, fullstack (BE heavy) with 10+ years of experience in software development. 
  Passionate about open source, blogging, and reading.
github:
  build_revision: "1.0.0"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://imdhemy.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: imdhemy
github_username: imdhemy

# -------------------------------------------------------------------------------------------------
# Build settings
# -------------------------------------------------------------------------------------------------
remote_theme: imdhemy/imdhemy-jekyll-theme
exclude:
  - Gemfile
  - Gemfile.lock
  - bin/

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-paginate
sass:
  quiet_deps: true # Suppress deprecation warnings from Sass

paginate: 7
paginate_path: "/blog/page:num/"
markdown: kramdown
permalink: /blog/:categories/:title:output_ext

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: "archive"
  permalinks:
    tag: '/tag/:name/'
    category: '/category/:name/'

# -------------------------------------------------------------------------------------------------
# Author
# -------------------------------------------------------------------------------------------------
author:
  name: Dhemy
  description: |
    I'm a software artist, fullstack (BE heavy) with 10+ years of experience in software development. 
    Passionate about open source, blogging, and reading.
  avatar: /theme/images/avatar.jpeg

# -------------------------------------------------------------------------------------------------
# Navigation
# -------------------------------------------------------------------------------------------------
navigation:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/blog"
  - title: "About"
    url: "/about"

# -------------------------------------------------------------------------------------------------
# Contributions
# -------------------------------------------------------------------------------------------------
contributions:
  - name: "Laravel"
    url: "https://laravel.com"
    logo: "theme/images/contributions/laravel.png"

  - name: "Spatie"
    url: "https://spatie.be/open-source"
    logo: "theme/images/contributions/spatie.png"

  - name: "Siklid"
    url: "https://docs.siklid.io/"
    logo: "theme/images/contributions/siklid.png"

  - name: "Google Play Billing"
    url: "https://github.com/imdhemy/google-play-billing"
    logo: "theme/images/contributions/google-play-billing.png"

  - name: "App Store IAP"
    url: "https://github.com/imdhemy/appstore-iap"
    logo: "theme/images/contributions/app-store-iap.png"

  - name: "Laravel In-app Purchase"
    url: "https://imdhemy.com/laravel-iap-docs/"
    logo: "theme/images/contributions/liap.png"

# -------------------------------------------------------------------------------------------------
# Testimonials
# -------------------------------------------------------------------------------------------------
testimonials:
  - name: "Dogan Aydin"
    description: "TurkNet CTO"
    image: "theme/images/testimonials/dogan-aydin.jpg"
    content: |
      Endorsing Dhemy for his exceptional coding skills and commitment to best practices. 
      With an R&D engineer mindset and meticulous approach to code structure, I highly recommend Dhemy to any company.

  - name: "Obada Qawwas"
    description: "Frontend Tech Lead at Valtech"
    image: "theme/images/testimonials/obada-qawwas.jpg"
    content: |
      Dhemy is one of the best among all people I have ever met and is a loyal colleague who understands complex matters. 
      He is a strong and goal-oriented team player; with every problem, there was a solution. Highly recommended.

  - name: "Abdelrahman Waziry"
    description: "Solutions Architect at TurnDigital"
    image: "theme/images/testimonials/abdelrahman-waziry.jpg"
    content: |
      Dhemy, an exceptional and innovative talent, consistently displays unwavering commitment and dedication in our collaborative projects, setting a stellar example for the ideal programmer.

# -------------------------------------------------------------------------------------------------
# Footer
# -------------------------------------------------------------------------------------------------
footer:
  bg_image: "/images/theme/social.png"
  social:
    - icon: "logo-github"
      url: "https://github.com/imdhemy"
    - icon: "logo-twitter"
      url: "https://twitter.com/imdhemy"
    - icon: "logo-linkedin"
      url: "https://www.linkedin.com/in/imdhemy/"
