name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Jekyll site.
        uses: fabacab/jekyll-builder-for-github-pages-action@v1 # Or whatever "@ref" you want.
